{% set name = "jdtls" %}
{% set version = "1.38.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/eclipse/eclipse.jdt.ls/archive/v{{ version }}.tar.gz
  sha256: bb2dec4d22e85224df24b69b629f4f60cf59d35bdb25a462a9b9f74ec6858f32

build:
  noarch: generic
  number: 0

requirements:
  build:
    - findutils
    - openjdk
  run:
    - openjdk
    - python

test:
  commands:
    - jdtls --help

about:
  home: https://github.com/eclipse/eclipse.jdt.ls
  license: EPL-2.0
  license_file:
    - LICENSE
    - target/generated-resources/licenses/
  summary: Java language specific implementation of the Language Server Protocol

extra:
  recipe-maintainers:
    - danielnachun
