context:
  version: "1.45.0"

package:
  name: jdtls
  version: ${{ version }}

source:
  url: https://github.com/eclipse/eclipse.jdt.ls/archive/v${{ version }}.tar.gz
  sha256: e16f5a01a879560ccace6e40c603c8837e2ec903f7e59ebf5ae8bc753fc32d00

build:
  number: 0
  noarch: generic

requirements:
  build:
    - findutils
    - openjdk
  run:
    - openjdk
    - python

tests:
  - script:
      - jdtls --help

about:
  license: EPL-2.0
  license_file:
    - LICENSE
    - target/generated-resources/licenses/
  summary: Java language specific implementation of the Language Server Protocol
  homepage: https://github.com/eclipse/eclipse.jdt.ls

extra:
  recipe-maintainers:
    - danielnachun
