context:
  version: "1.44.0"

package:
  name: jdtls
  version: ${{ version }}

source:
  url: https://github.com/eclipse/eclipse.jdt.ls/archive/v${{ version }}.tar.gz
  sha256: 785cac55f6ce54395d2e0bd2e16a49b46cd48b83732273962c9eb268f83f521a

build:
  number: 0
  noarch: generic

requirements:
  build:
    - findutils
    - openjdk
  run:
    - openjdk
    - python

tests:
  - script:
      - jdtls --help

about:
  license: EPL-2.0
  license_file:
    - LICENSE
    - target/generated-resources/licenses/
  summary: Java language specific implementation of the Language Server Protocol
  homepage: https://github.com/eclipse/eclipse.jdt.ls

extra:
  recipe-maintainers:
    - danielnachun
