context:
  version: "1.46.0"

package:
  name: jdtls
  version: ${{ version }}

source:
  url: https://github.com/eclipse/eclipse.jdt.ls/archive/v${{ version }}.tar.gz
  sha256: 9ff00d0b4977b364c0752ed3e2a971a055b47ff63ba421aec808cbab0b734896

build:
  number: 0
  noarch: generic

requirements:
  build:
    - findutils
    - openjdk
  run:
    - openjdk
    - python

tests:
  - script:
      - jdtls --help

about:
  license: EPL-2.0
  license_file:
    - LICENSE
    - target/generated-resources/licenses/
  summary: Java language specific implementation of the Language Server Protocol
  homepage: https://github.com/eclipse/eclipse.jdt.ls

extra:
  recipe-maintainers:
    - danielnachun
