context:
  version: "1.54.0"

package:
  name: jdtls
  version: ${{ version }}

source:
  url: https://github.com/eclipse/eclipse.jdt.ls/archive/v${{ version }}.tar.gz
  sha256: 586454a1799357ee7c01c0789840fed4212cae249a239c9b20b7b79fc3105f20

build:
  number: 0
  noarch: generic

requirements:
  build:
    - findutils
    - openjdk
  run:
    - openjdk
    - python

tests:
  - script:
      - jdtls --help

about:
  license: EPL-2.0
  license_file:
    - LICENSE
    - target/generated-resources/licenses/
  summary: Java language specific implementation of the Language Server Protocol
  homepage: https://github.com/eclipse/eclipse.jdt.ls

extra:
  recipe-maintainers:
    - danielnachun
