context:
  version: "1.58.0"

package:
  name: jdtls
  version: ${{ version }}

source:
  url: https://github.com/eclipse/eclipse.jdt.ls/archive/v${{ version }}.tar.gz
  sha256: 213131a7e12fdad3800defafa806c3cf7dc9367fd3825f9043646e07caea44ee

build:
  number: 0
  noarch: generic

requirements:
  build:
    - findutils
    - openjdk
  run:
    - openjdk
    - python

tests:
  - script:
      - jdtls --help

about:
  license: EPL-2.0
  license_file:
    - LICENSE
    - target/generated-resources/licenses/
  summary: Java language specific implementation of the Language Server Protocol
  homepage: https://github.com/eclipse/eclipse.jdt.ls

extra:
  recipe-maintainers:
    - danielnachun
